from __future__ import annotations

from dataclasses import dataclass, field
from random import Random


DIRECTIONS = {
    "N": (0, -1),
    "S": (0, 1),
    "E": (1, 0),
    "W": (-1, 0),
}

OPPOSITE = {"N": "S", "S": "N", "E": "W", "W": "E"}


@dataclass
class Cell:
    x: int
    y: int
    walls: dict[str, bool] = field(
        default_factory=lambda: {"N": True, "S": True, "E": True, "W": True}
    )


class Maze:
    """Grid maze generated by iterative DFS/backtracking plus a few extra loops."""

    def __init__(
        self,
        width: int,
        height: int,
        seed: int | None = None,
        extra_passage_ratio: float = 0.08,
    ) -> None:
        if width < 2 or height < 2:
            raise ValueError("Maze dimensions must be at least 2x2.")
        self.width = width
        self.height = height
        self.seed = seed
        self.extra_passage_ratio = extra_passage_ratio
        self.random = Random(seed)
        self.grid = [[Cell(x, y) for x in range(width)] for y in range(height)]
        self.start = (0, 0)
        self.goal = (width - 1, height - 1)
        self.generate()

    def generate(self) -> None:
        """Regenerate the maze using an explicit stack."""
        for row in self.grid:
            for cell in row:
                cell.walls = {"N": True, "S": True, "E": True, "W": True}

        stack = [self.start]
        visited = {self.start}

        while stack:
            current = stack[-1]
            unvisited = [
                (direction, neighbor)
                for direction, neighbor in self._neighbor_positions(current)
                if neighbor not in visited
            ]
            if not unvisited:
                stack.pop()
                continue

            direction, nxt = self.random.choice(unvisited)
            self._remove_wall(current, nxt, direction)
            visited.add(nxt)
            stack.append(nxt)

        self._carve_extra_passages()

    def cell(self, position: tuple[int, int]) -> Cell:
        x, y = position
        return self.grid[y][x]

    def _neighbor_positions(
        self, position: tuple[int, int]
    ) -> list[tuple[str, tuple[int, int]]]:
        x, y = position
        neighbors: list[tuple[str, tuple[int, int]]] = []
        for direction, (dx, dy) in DIRECTIONS.items():
            nx, ny = x + dx, y + dy
            if 0 <= nx < self.width and 0 <= ny < self.height:
                neighbors.append((direction, (nx, ny)))
        return neighbors

    def _remove_wall(
        self, current: tuple[int, int], nxt: tuple[int, int], direction: str
    ) -> None:
        current_cell = self.cell(current)
        next_cell = self.cell(nxt)
        current_cell.walls[direction] = False
        next_cell.walls[OPPOSITE[direction]] = False

    def _carve_extra_passages(self) -> None:
        """Open a few extra walls so the maze is not always a single-solution tree."""
        candidates: list[tuple[tuple[int, int], tuple[int, int], str]] = []

        for y in range(self.height):
            for x in range(self.width):
                current = (x, y)
                cell = self.cell(current)
                if x + 1 < self.width and cell.walls["E"]:
                    candidates.append((current, (x + 1, y), "E"))
                if y + 1 < self.height and cell.walls["S"]:
                    candidates.append((current, (x, y + 1), "S"))

        if not candidates:
            return

        extra_count = max(1, round(self.width * self.height * self.extra_passage_ratio))
        extra_count = min(extra_count, len(candidates))

        for current, nxt, direction in self.random.sample(candidates, extra_count):
            if self.cell(current).walls[direction]:
                self._remove_wall(current, nxt, direction)

    def accessible_neighbors(self, position: tuple[int, int]) -> list[tuple[int, int]]:
        cell = self.cell(position)
        neighbors: list[tuple[int, int]] = []
        for direction, (dx, dy) in DIRECTIONS.items():
            if not cell.walls[direction]:
                neighbors.append((position[0] + dx, position[1] + dy))
        return neighbors

    def path_cost(self, path: list[tuple[int, int]]) -> int:
        return max(0, len(path) - 1)

    def to_ascii(
        self,
        path: set[tuple[int, int]] | None = None,
        explored: set[tuple[int, int]] | None = None,
    ) -> str:
        path = path or set()
        explored = explored or set()
        top = "+" + "---+" * self.width
        rows = [top]
        for y in range(self.height):
            body = ["|"]
            floor = ["+"]
            for x in range(self.width):
                cell = self.grid[y][x]
                pos = (x, y)
                if pos == self.start:
                    mark = " S "
                elif pos == self.goal:
                    mark = " G "
                elif pos in path:
                    mark = " * "
                elif pos in explored:
                    mark = " . "
                else:
                    mark = "   "
                body.append(mark)
                body.append("|" if cell.walls["E"] else " ")
                floor.append("---+" if cell.walls["S"] else "   +")
            rows.append("".join(body))
            rows.append("".join(floor))
        return "\n".join(rows)
